local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerScriptService = game:GetService("ServerScriptService")

local RemoteEvents = require(ReplicatedStorage.Remotes.RemoteEvents)
local LevelSetup = require(ServerScriptService.Gameplay.LevelSetup)
local DataHandler = require(ServerScriptService.Data.DataHandler)
local AntiCheatService = require(ServerScriptService.AntiCheat.AntiCheatService)
local VehicleAssemblyService = require(ServerScriptService.Vehicles.VehicleAssemblyService)
local VehicleDrivingService = require(ServerScriptService.Vehicles.VehicleDrivingService)
local VolatileCargoService = require(ServerScriptService.Physics.VolatileCargoService)
local ProjectileService = require(ServerScriptService.Physics.ProjectileService)
local TestDummyService = require(ServerScriptService.Physics.TestDummyService)
local ContractService = require(ServerScriptService.Economy.ContractService)
local FTUEController = require(ServerScriptService.Gameplay.FTUEController)
local SoftPermadeathService = require(ServerScriptService.Gameplay.SoftPermadeathService)
local ExtractionZoneService = require(ServerScriptService.Gameplay.ExtractionZoneService)
local RaiderService = require(ServerScriptService.Gameplay.RaiderService)

RemoteEvents.Init()
LevelSetup.Init()
DataHandler.Init()
AntiCheatService.Init()
VehicleAssemblyService.Init()
VehicleDrivingService.Init()
VolatileCargoService.Init()
ProjectileService.Init()
TestDummyService.Init()
ContractService.Init()
FTUEController.Init()
SoftPermadeathService.Init()
ExtractionZoneService.Init()
RaiderService.Init()
