local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerScriptService = game:GetService("ServerScriptService")

local RemoteEvents = require(ReplicatedStorage.Remotes.RemoteEvents)
local LevelSetup = require(ServerScriptService.Gameplay.LevelSetup)
local DataHandler = require(ServerScriptService.Data.DataHandler)
local AntiCheatService = require(ServerScriptService.AntiCheat.AntiCheatService)
local VehicleAssemblyService = require(ServerScriptService.Vehicles.VehicleAssemblyService)
local VolatileCargoService = require(ServerScriptService.Physics.VolatileCargoService)
local ContractService = require(ServerScriptService.Economy.ContractService)
local FTUEController = require(ServerScriptService.Gameplay.FTUEController)
local SoftPermadeathService = require(ServerScriptService.Gameplay.SoftPermadeathService)
local ExtractionZoneService = require(ServerScriptService.Gameplay.ExtractionZoneService)

RemoteEvents.Init()
LevelSetup.Init()
DataHandler.Init()
AntiCheatService.Init()
VehicleAssemblyService.Init()
VolatileCargoService.Init()
ContractService.Init()
FTUEController.Init()
SoftPermadeathService.Init()
ExtractionZoneService.Init()
